Dashboard tile
creacoon/laravel-dashboard-gitlab-user-counts-tile pull request #2
Opened 2024-09-02 09:02 UTC by JulianaChiabai

2024-09-02 09:07 UTC, JulianaChiabai reviewed
.

2024-09-03 09:19 UTC, tomcoonen requested changes

2024-09-03 09:19 UTC, tomcoonen commented on src/GitLabTileServiceProvider.php
Would be good to make this tile more specific, like `GitLabUserCountsTitle` so it reflects what is does.

2024-09-03 09:19 UTC, tomcoonen commented on tests/ExampleTest.php
Test namespace is wrong.

2024-09-03 09:19 UTC, tomcoonen commented on src/FetchDataFromApiCommand.php
API endpoint should be configurable, and we should show initials on the tile instead of full usernames so it's more in line with the rest.

2024-09-03 09:19 UTC, tomcoonen commented on CHANGELOG.md
Replace `:package_name` please.

2024-09-04 09:34 UTC, tomcoonen requested changes

2024-09-04 09:34 UTC, tomcoonen commented on src/FetchDataFromGitLabUserCountsCommand.php
> +        $specificUsers = $gitlabConfig['specific_users'];
Please use the configs directly, this helps them to be found, and you can easily click through in the IDE.
So e.g. `config('dashboard.tiles.gitlab.specific_users')`.

2024-09-05 06:46 UTC, merged